### ISSUE TITLE
Problem writing eleventy templates (more info in DEBUG output)

### ISSUE THREAD

**Issue by kylesloper** [danurbanowicz/eleventy-netlify-boilerplate#59]
##### Here is the DEBUG output:

Error with passthrough copy: (more in DEBUG output)

> Having trouble copying './static/img'

`TemplatePassthroughManagerCopyError` was thrown

> EPERM: operation not permitted, open 'C:\Users\kyles\Desktop\moonface\_site\static\img\715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm'

`Error` was thrown:

Unhandled rejection in promise ([object Promise]): (more in DEBUG output)

> Having trouble copying

`TemplateWriterWriteError` was thrown

> Having trouble copying './static/img'

`TemplatePassthroughManagerCopyError` was thrown

> EPERM: operation not permitted, open 'C:\Users\kyles\Desktop\moonface\_site\static\img\715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm'

`Error` was thrown:

    Error: EPERM: operation not permitted, open 'C:\Users\kyles\Desktop\moonface\_site\static\img\715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm'

    Error: EPERM: operation not permitted, open 'C:\Users\kyles\Desktop\moonface\_site\static\img\715580bf-9f2c-4e74-b0c5-7649f02ebfa1.webm'

Problem writing Eleventy templates: (more in DEBUG output)

> Output conflict: multiple input files are writing to `_site/authors/the-moonface-team/index.html`. Use distinct `permalink` values to resolve this conflict.

  1. ./author.njk

  2. ./author.njk

`DuplicatePermalinkOutputError` was thrown:

    (Repeated output has been truncated...)

        at TemplateMap.checkForDuplicatePermalinks (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateMap.js:547:13)

        at TemplateMap.cache (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateMap.js:308:10)      

        at processTicksAndRejections (internal/process/task_queues.js:93:5)

        at async TemplateWriter._createTemplateMap (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateWriter.js:170:5)

        at async TemplateWriter.writeTemplates (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateWriter.js:203:5)

        at async TemplateWriter.write (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateWriter.js:254:25)

        at async Eleventy.write (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Eleventy.js:743:13)      

        at async Eleventy._watch (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Eleventy.js:488:5)      

        at async Timeout._onTimeout (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Eleventy.js:678:11)  

Copied 19 files / Wrote 0 files in 1.78 seconds (v0.11.1)

Watching...

[Browsersync] Reloading Browsers...

File changed: posts\christmas-wishes-from-moonface.md

Problem writing Eleventy templates: (more in DEBUG output)

    (Repeated output has been truncated...)

        at TemplateMap.checkForDuplicatePermalinks (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateMap.js:547:13)

        at TemplateMap.cache (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateMap.js:308:10)      

        at runMicrotasks (<anonymous>)

        at processTicksAndRejections (internal/process/task_queues.js:93:5)

        at async TemplateWriter._createTemplateMap (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateWriter.js:170:5)

        at async TemplateWriter.writeTemplates (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateWriter.js:203:5)

        at async TemplateWriter.write (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\TemplateWriter.js:254:25)

        at async Eleventy.write (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Eleventy.js:743:13)      

        at async Eleventy._watch (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Eleventy.js:488:5)      

        at async Timeout._onTimeout (C:\Users\kyles\Desktop\moonface\node_modules\@11ty\eleventy\src\Eleventy.js:678:11)  

Copied 34 files / Wrote 0 files in 0.98 seconds (v0.11.1)

Watching...

**Comment by danurbanowicz** [comment]
This is probably because the image file type of .webm that you’re trying to do a passThroughCopy on isn’t recognised and needs to be specified explicitly in your .eleventy.js config file.

See the following issue for details on how to do that: https://github.com/11ty/eleventy/issues/317

Hopefully that helps!

**Comment by danurbanowicz** [comment]
I'm closing this issue now but if the problem persists, please feel free to re-open!
